let dados = [
    {
        nome:"Edmund Husserl",
        alt:"Foto Edmund_Husserl",
        capa:"edmund_husserl.jpg",
        descricao:"Fundador da fenomenologia, suas ideias influenciaram profundamente a psicologia fenomenológica.",
        subtitulo1:"Principais Conceitos:",
        conceito1:"Intencionalidade:",
        conceito11:"Ato de consciência está sempre direcionado a algo; a consciência é sempre intencional.",
        conceito2:"Redução Fenomenológica:",
        conceito22:"Suspender julgamentos sobre a realidade externa para focar na experiência pura da consciência.",
        conceito3:"Essências:",
        conceito33:"Fenomenologia busca entender a essência das experiências ao descrever como elas aparecem na consciência",
        subtitulo2:"Principais Obras:",
        Obra1: "Ideias gerais sobre a fenomenologia",
        Obra2: "As investigações lógicas",
        link:"https://pt.wikipedia.org/wiki/Edmund_Husserl",
        tags: "Fenomenologia Intencionalidade"
    },

    {
        nome:"Martin Heidegger",
        alt: "Foto Martin Heidegger",
        capa:"martin_heidegger.jpg",
        descricao: "Filósofo existencialista alemão, conhecido por sua obra 'Ser e Tempo'.",
        subtitulo1:"Principais Conceitos:",
        conceito1: "Ser-aí:",
        conceito11: "O ser humano como ser-no-mundo, lançado no mundo e sempre em relação a ele.",
        conceito2: "Tempo:",
        conceito22:" A temporalidade como constitutiva da existência humana.",
        conceito3: "Angústia:",
        conceito33: "A experiência fundamental da finitude e da possibilidade da não-autenticidade.",
        subtitulo2:"Principais Obras:",
        Obra1: "Ser e tempo",
        Obra2: "Caminhos da floresta",
        tags: "Existencialismo Ser e Tempo",
        link: "https://pt.wikipedia.org/wiki/Martin_Heidegger"
      },

      {
        nome: "Maurice Merleau-Ponty",
        alt: "Foto Maurice Merleau-Ponty",
        capa:"maurice_merleau_ponty.jpg",
        descricao: "Filósofo francês, conhecido por sua fenomenologia da percepção.",
        subtitulo1:"Principais Conceitos:",
        conceito1: "Corpo:",
        conceito11: "O corpo como sujeito e objeto da experiência, como meio de relação com o mundo.",
        conceito2: "Percepção:",
        conceito22:" A percepção como uma experiência ativa e intencional, não como uma mera recepção de dados sensoriais.",
        subtitulo2:"Principais Obras:",
        Obra1:"Fenomenologia da percepção",
        Obra2: "O visível e o invisível",
        tags: "Percepção Corpo",
        link: "https://pt.wikipedia.org/wiki/Maurice_Merleau-Ponty"
      },
      {
        nome: "Jean-Paul Sartre",
        alt: "Foto Jean-Paul Sartre",
        capa:"jean_paul_sartre.jpg",
        descricao: "Filósofo existencialista francês, dramaturgo e romancista, conhecido por sua obra 'O Ser e o Nada'.",
        subtitulo1:"Principais Conceitos:",
        conceito1: "Existência precede a essência:",
        conceito11: "O ser humano não possui uma natureza pré-definida, mas se define através de suas escolhas.",
        conceito2: "Má-fé:",
        conceito22:" A negação da liberdade, a tentativa de fugir da responsabilidade pelas próprias escolhas.",
        conceito3: "Olhar do outro:",
        conceito33: "A influência do olhar alheio na construção da identidade.",
        subtitulo2:"Principais Obras:",
        Obra1:"O ser e o nada",
        Obra2:"As moscas",
        tags:"Existencialismo Liberdade",
        link: "https://pt.wikipedia.org/wiki/Jean_Paul_Sartre"
      },
      {
        nome: "Karl Jaspers",
        alt: "Foto Karl Jaspers",
        capa:"karl_jaspers.jpg",
        descricao: "Filósofo existencialista alemão, psiquiatra e filósofo da religião.",
        subtitulo1:"Principais Conceitos:",
        conceito1: "Situação-limite:",
        conceito11: "Experiências existenciais que revelam a finitude e a transcendência humana (morte, culpa, sofrimento).",
        conceito2: "Razão transcendente:",
        conceito22:"Uma razão que ultrapassa os limites da razão instrumental e busca o sentido da existência.",
        conceito3: "Consciência de si:",
        conceito33: "A capacidade humana de tomar consciência de si mesma e de sua liberdade.",
        subtitulo2:"Principais Obras:",
        Obra1:"Psicologia das grandes linhas",
        Obra2:"A razão na época do cientificismo",
        tags: "Existencialismo Situação-limite",
        link: "https://pt.wikipedia.org/wiki/Karl_Jaspers"
      },
      {
        nome: "Ludwig Binswanger",
        alt: "Foto Ludwig Binswanger",
        capa:"ludwig_binswanger.jpg",
        descricao: "Psiquiatra suíço e um dos fundadores da psicoterapia existencial.",
        subtitulo1:"Principais Conceitos:",
        conceito1: "Mundo do paciente:",
        conceito11: "A importância de compreender o mundo subjetivo do paciente para tratar doenças mentais.",
        conceito2: "Existência autêntica:",
        conceito22:"A busca por uma vida significativa e autêntica, em oposição a uma existência alienada.",
        conceito3: "Relação médico-paciente:",
        conceito33: "A importância de uma relação terapêutica baseada na compreensão e empatia.",
        subtitulo2:"Principais Obras:",
        Obra1:"O ser como problema",
        Obra2:"Três modalidades do ser",
        tags: "Psicoterapia Existencial Existência Autêntica",
        link: "https://en.wikipedia.org/wiki/Ludwig_Binswanger"
      }
];